services:
  - type: web
    name: news-automation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn asgi:app --host 0.0.0.0 --port $PORT
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /data/news.db
