cmd: uvicorn news_automation:app --host 0.0.0.0 --port $PORT
env:
  DB_PATH: /data/news.db
  REWRITE_WITH_AI: "1"
  OPENROUTER_API_KEY: "<sua chave aqui>"
  DEFAULT_KEYWORDS: "litoral-norte-de-sao-paulo"
  REQUIRE_H1: "true"
  REQUIRE_IMAGE: "true"
  MIN_WORDS: "200"
  CRON_INTERVAL_MIN: "15"
